### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by tthomxs** [battleless/kick-api-wrapper#1]
https://kick.com/api/v2/channels/${user}/leaderboards - To add the leaderboard data for a streamer/users streams

https://kick.com/api/v2/clips/${clip_id}/info - Adding information for single clip instead of multiple

https://kick.com/api/v1/users/${user} - Adding easy to access data for users without the bulk of stream info

Would be amazing if you added these, thanks! 
P.S nice NPM package, very useful!

**Comment by battleless** [comment]
added here: https://github.com/battleless/kick-api-wrapper/commit/3f274fc40be44f3f34930f2a12f5ff66548531b3
